<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'emberlabs\\gravatarlib\\' => array($vendorDir . '/emberlabs/gravatarlib'),
    'PHPExcel' => array($vendorDir . '/codeplex/phpexcel'),
    'Mouf\\Utils\\Cache' => array($vendorDir . '/mouf/utils.cache.cache-interface/src', $vendorDir . '/mouf/utils.cache.in-memory-cache/src'),
);
